### ISSUE TITLE
Disable Desktop Notifications

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix#133]
Upon first startup the Meilix pollutes the screen with LXQT notifications. So the question is how to turn them off or silence or tweak them? How to "fix them" in so far they demonstrate an error?

Hints for research:
https://github.com/lxde/lxqt-notificationd
https://wiki.archlinux.org/index.php/Desktop_notifications

**Comment by meets2tarun** [comment]
What does the `junior job` mean here?

**Comment by xeon-zolt** [comment]
attempted removing library responsible for notification but some apps still can send notifications

**Comment by tabesin** [comment]
What I read online in LXQT forums is that removing does not work. You just have to turn the demon off or clear or resolve the messages. Which hints at the metapackage box.

JuniorJob = well contained easy hack.

**Comment by meets2tarun** [comment]
![screenshot_fghjkl_2017-08-09_04 24 02](https://user-images.githubusercontent.com/15213246/29098027-bb219946-7cba-11e7-91d1-d94eea727f63.png)

**Comment by tabesin** [comment]
Now only the lxqt panel warning about registering a shortcuts prevails, that seems to be a bug in lxqt but can be solved by editing the configuration that causes it.

**Comment by tabesin** [comment]
Explained here https://github.com/lxde/lxqt/issues/1032 with regards to openbox.

It is basically that the display manager registers it before. We are not using openbox, right? So consider to file a bug upstream as it affects our display manager as well.

**Comment by tabesin** [comment]
Let's see if I fixed that.

**Comment by xeon-zolt** [comment]
> We are not using openbox, right? 

we are using opebox

**Comment by meets2tarun** [comment]
Show desktop error still persists. I checked it in the latest iso release in the FOSSASIA repo.

**Comment by meets2tarun** [comment]
@tabesin, We require your help here
We tried whole way but we aren't successful.

**Comment by tabesin** [comment]
Ok, have a look at the notification demons and how to generate notiffications and how to stop them.

**Comment by tabesin** [comment]
No, you just need to pull the notifications that show up at startup.
1)  by resolving the cause that triggers the notifications first place
2) by killing the notifications that appear upon startup

This does not involve taking down the notification system altogether or hiding the notifications via theming, these are ugly and insufficent workarounds.

Get familiar with the notification demon. There must be a killall option. As we are using LXQT feel free to get informed by the lxqt notification demon developers how to killall notifications or implement such an option in their repo.

**Comment by meets2tarun** [comment]
@tabesin I tried killing the notification in this https://github.com/fossasia/meilix/pull/165 but it didn't work.

**Comment by tabesin** [comment]
Have you asked the LXQT developers on IRC or whatever channel they use?

**Comment by xeon-zolt** [comment]
no reply yet on reddit
let me check on IRC

**Comment by sandeepsajan0** [comment]
Can I work on this issue?

**Comment by meets2tarun** [comment]
Sandeep
Go for it! We will wait for your PR.

**Comment by tabesin** [comment]
dbus-send --type=method_call\
--dest=org.freedesktop.Notifications\
/org/freedesktop/Notifications\
org.freedesktop.Notifications.CloseNotification uint32:0

**Comment by tabesin** [comment]
see https://gist.github.com/baverman/6440898

**Comment by pranav1698** [comment]
We can try removing lxqt-notificationd by:
sudo rm /usr/bin/lxqt-notificationd
@tabesin @meets2tarun?

**Comment by tabesin** [comment]
The task is to resolve of kill the default startup notifications. not to remove the notification demon as such.
